# Generated by Django 5.2 on 2025-05-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
